export const weatherActionTypes = {
    GET_REQUEST: 'GET_REQUEST',
    REQUEST_SUCCEED: 'REQUEST_SUCCEED',
    SET_LOADING_STATE: 'SET_LOADING_STATE',
    SET_ERROR_STATE: 'SET_ERROR_STATE',
    GET_TEST_SAGA: 'GET_TEST_SAGA'
};
