export const weatherActionTypes = {
    GET_REQUEST: 'GET_REQUEST',
    REQUEST_SUCCEED: 'REQUEST_SUCCEED',
    SET_LOADING_STATE: 'SET_LOADING_STATE',
    SET_ERROR_STATE: 'SET_ERROR_STATE',
    GET_TEST_SAGA: 'GET_TEST_SAGA',
    CHANNEL_START: 'CHANNEL_START',
    CHANNEL_STOP: 'CHANNEL_STOP',
    SET_CHANNEL_STATUS: 'SET_CHANNEL_STATUS',
    SET_SERVER_STATUS: 'SET_SERVER_STATUS'
};
